site_name: Pan Docs
site_description: Documentation and Tutorials for Pan framework.
site_author: 'nius, campusapp.cn'
site_url: 'http://blog.campusapp.cn/Pan-Documentation/'
theme: 'material'

repo_name: 'GitHub'
repo_url: 'https://github.com/campusappcn/Pan'

copyright: 'Copyright (c) 2016 杭州树洞网络科技有限公司'

extra:
  palette:
  # http://www.materialui.co/colors
  # Valid values are: red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey and blue grey. The last three colors can only be used as a primary color.
    primary: 'indigo'
    accent: 'light blue'

markdown_extensions:
  #https://pythonhosted.org/Markdown/extensions/admonition.html
  - admonition
  - codehilite(css_class=code)

#防止javadoc的css被合并
extra_css:
  - ''

pages:
  - Home: index.md
  - Getting Started: Getting_Started.md
  - Components: Components.md
  - 复用：继承和委托: 复用_继承和委托.md
  - ViewHolder模式和嵌套使用: ViewHolder模式和嵌套使用.md
  - 常用的ViewModel实现类: 常用的ViewModel实现类.md
  - 插件系统: 拓展_插件系统.md
  - MVVM和MVP: MVVM_MVP.md
  - 集成Data-Binding: 集成Data-Binding.md
  - 常见问题: 常见问题.md